// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/smithery": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/smithery";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/smithery.ts": {
    id: "routes/smithery";
    page: "/smithery";
  };
};