// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/docs/:path": {
    params: {
      "path": string;
    };
  };
  "/smithery": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/docs" | "/docs/:path" | "/smithery";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/docs._index.tsx": {
    id: "routes/docs._index";
    page: "/docs";
  };
  "routes/docs.$path.tsx": {
    id: "routes/docs.$path";
    page: "/docs/:path";
  };
  "routes/smithery.ts": {
    id: "routes/smithery";
    page: "/smithery";
  };
};